### ISSUE TITLE
[Code Addition Request]: Manga/Anime Tracker

### ISSUE THREAD

**Issue by KiranBaliga** [UTSAVS26/PyVerse#599]
### Have you completed your first issue?

- [X] I have completed my first issue

### Guidelines

- [X] I have read the guidelines
- [ ] I have the link to my latest merged PR

### Latest Merged PR Link

N/A

### Project Description

Project: Manga/Anime Tracker and Recommender

Objective: Build a Python application where users can track the manga they are reading or anime they are watching, rate them, and get personalized recommendations based on their preferences.

### Full Name

Kiran Baliga

### Participant Role

GSSOC-Ext
